/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tarea1_HijosDelCodigo;

/**
 *
 * @author Luisf
 */
public class Control_JavaSwing_Menus extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Control_JavaSwing_Menus.class.getName());

    /**
     * Creates new form Control_JavaSwing_Menus
     */
    public Control_JavaSwing_Menus() {
        initComponents();
        jmbBarraPrincipal.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jmbBarraPrincipal = new javax.swing.JMenuBar();
        jmReproducir = new javax.swing.JMenu();
        jmCancion1 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jmControles = new javax.swing.JMenu();
        jmAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 998, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 963, Short.MAX_VALUE)
        );

        jmbBarraPrincipal.setBackground(new java.awt.Color(204, 255, 255));
        jmbBarraPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jmbBarraPrincipal.setToolTipText("Menu Principal de la aplicacion de musica");
        jmbBarraPrincipal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jmbBarraPrincipal.setOpaque(true);
        jmbBarraPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jmbBarraPrincipalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jmbBarraPrincipalMouseExited(evt);
            }
        });
        jmbBarraPrincipal.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jmbBarraPrincipalComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jmbBarraPrincipalComponentShown(evt);
            }
        });

        jmReproducir.setBackground(new java.awt.Color(204, 204, 204));
        jmReproducir.setMnemonic('R');
        jmReproducir.setText("Reproducir");
        jmReproducir.setOpaque(true);
        jmReproducir.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
                jmReproducirMenuCanceled(evt);
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
                jmReproducirMenuDeselected(evt);
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jmReproducirMenuSelected(evt);
            }
        });

        jmCancion1.setBackground(new java.awt.Color(204, 255, 255));
        jmCancion1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jmCancion1.setText("Cancion1");
        jmCancion1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jmCancion1.setOpaque(true);
        jmReproducir.add(jmCancion1);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOpaque(true);
        jmReproducir.add(jSeparator1);

        jMenuItem1.setText("Cancion2");
        jmReproducir.add(jMenuItem1);

        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jmReproducir.add(jMenuItem2);

        jmbBarraPrincipal.add(jmReproducir);

        jmControles.setBackground(new java.awt.Color(204, 204, 204));
        jmControles.setMnemonic('C');
        jmControles.setText("Controles");
        jmControles.setOpaque(true);
        jmControles.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
                jmControlesMenuCanceled(evt);
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
                jmControlesMenuDeselected(evt);
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jmControlesMenuSelected(evt);
            }
        });
        jmbBarraPrincipal.add(jmControles);

        jmAyuda.setBackground(new java.awt.Color(204, 204, 204));
        jmAyuda.setMnemonic('A');
        jmAyuda.setText("Ayuda");
        jmAyuda.setOpaque(true);
        jmAyuda.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
                jmAyudaMenuDeselected(evt);
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jmAyudaMenuSelected(evt);
            }
        });
        jmbBarraPrincipal.add(jmAyuda);

        setJMenuBar(jmbBarraPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmbBarraPrincipalComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jmbBarraPrincipalComponentShown
        System.out.println("La barra principal del menu ahora esta visible");
    }//GEN-LAST:event_jmbBarraPrincipalComponentShown

    private void jmbBarraPrincipalComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jmbBarraPrincipalComponentHidden
        System.out.println("La barra principal del menu ahora esta oculta");
    }//GEN-LAST:event_jmbBarraPrincipalComponentHidden

    private void jmbBarraPrincipalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmbBarraPrincipalMouseEntered
        System.out.println("El mouse entro en la barra principal");
    }//GEN-LAST:event_jmbBarraPrincipalMouseEntered

    private void jmbBarraPrincipalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmbBarraPrincipalMouseExited
        System.out.println("El mouse salio de la barra principal");
    }//GEN-LAST:event_jmbBarraPrincipalMouseExited

    private void jmReproducirMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jmReproducirMenuSelected
       System.out.println("El menu de reproducir esta abierto");
    }//GEN-LAST:event_jmReproducirMenuSelected

    private void jmReproducirMenuDeselected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jmReproducirMenuDeselected
        System.out.println("El menu de reproducir esta cerrado");
    }//GEN-LAST:event_jmReproducirMenuDeselected

    private void jmReproducirMenuCanceled(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jmReproducirMenuCanceled
        System.out.println("El menu de reproducir se cancelo");
    }//GEN-LAST:event_jmReproducirMenuCanceled

    private void jmControlesMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jmControlesMenuSelected
        System.out.println("El menu de controles esta abierto");
    }//GEN-LAST:event_jmControlesMenuSelected

    private void jmControlesMenuDeselected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jmControlesMenuDeselected
        System.out.println("El menu de controles esta cerrado");
    }//GEN-LAST:event_jmControlesMenuDeselected

    private void jmControlesMenuCanceled(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jmControlesMenuCanceled
        System.out.println("El menu de controles se cancelo");
    }//GEN-LAST:event_jmControlesMenuCanceled

    private void jmAyudaMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jmAyudaMenuSelected
        System.out.println("El menu de ayuda esta abierto");
    }//GEN-LAST:event_jmAyudaMenuSelected

    private void jmAyudaMenuDeselected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jmAyudaMenuDeselected
        System.out.println("El menu de ayuda esta cerrado");
    }//GEN-LAST:event_jmAyudaMenuDeselected

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Control_JavaSwing_Menus().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu jmAyuda;
    private javax.swing.JMenu jmCancion1;
    private javax.swing.JMenu jmControles;
    private javax.swing.JMenu jmReproducir;
    private javax.swing.JMenuBar jmbBarraPrincipal;
    // End of variables declaration//GEN-END:variables
}
