/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tarea1_HijosDelCodigo;

import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import javax.swing.JPanel;

/**
 *
 * @author Luisf
 */
public class Control_JavaSwing_Menus extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Control_JavaSwing_Menus.class.getName());

    /**
     * Creates new form Control_JavaSwing_Menus
     */
    public Control_JavaSwing_Menus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        Opcion1 = new javax.swing.JMenuItem();
        Opcion2 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu1 = new javax.swing.JMenu();
        SubOpcion = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        lblRepetir = new javax.swing.JLabel();
        btnAlternarMenu = new javax.swing.JButton();
        jmbBarraPrincipal = new javax.swing.JMenuBar();
        jmReproducir = new javax.swing.JMenu();
        jmCancion1 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jmControles = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        chkRepetirCancion = new javax.swing.JCheckBoxMenuItem();
        modoOscuroItem = new javax.swing.JMenu();
        modoClaroItem = new javax.swing.JRadioButtonMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();

        Opcion1.setText("Abrir");
        jPopupMenu1.add(Opcion1);

        Opcion2.setText("Actualizar");
        jPopupMenu1.add(Opcion2);
        jPopupMenu1.add(jSeparator2);

        jMenu1.setText("nuevo");

        SubOpcion.setText("Archivo Vacio");
        jMenu1.add(SubOpcion);

        jMenuItem3.setText("Archivo vacio2");
        jMenu1.add(jMenuItem3);

        jPopupMenu1.add(jMenu1);
        jPopupMenu1.add(jSeparator3);

        jMenuItem4.setText("Salir");
        jPopupMenu1.add(jMenuItem4);

        jMenu2.setText("File");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel1.setComponentPopupMenu(jPopupMenu1);

        lblRepetir.setText("Repetir: OFF");

        btnAlternarMenu.setBackground(new java.awt.Color(204, 204, 204));
        btnAlternarMenu.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAlternarMenu.setText("Alternar menu");
        btnAlternarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlternarMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(782, Short.MAX_VALUE)
                .addComponent(lblRepetir)
                .addGap(76, 76, 76))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnAlternarMenu)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(btnAlternarMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 655, Short.MAX_VALUE)
                .addComponent(lblRepetir)
                .addGap(31, 31, 31))
        );

        jmbBarraPrincipal.setBackground(new java.awt.Color(204, 255, 255));
        jmbBarraPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jmbBarraPrincipal.setToolTipText("Menu Principal de la aplicacion de musica");
        jmbBarraPrincipal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jmbBarraPrincipal.setOpaque(true);
        jmbBarraPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jmbBarraPrincipalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jmbBarraPrincipalMouseExited(evt);
            }
        });
        jmbBarraPrincipal.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jmbBarraPrincipalComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jmbBarraPrincipalComponentShown(evt);
            }
        });

        jmReproducir.setBackground(new java.awt.Color(204, 204, 204));
        jmReproducir.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luisf\\OneDrive\\Documentos\\ProyectosJava\\Tarea1HijosDelCodigo\\src iconos\\playbutton_120627.png")); // NOI18N
        jmReproducir.setMnemonic('R');
        jmReproducir.setText("Reproducir");
        jmReproducir.setOpaque(true);
        jmReproducir.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
                jmReproducirMenuCanceled(evt);
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
                jmReproducirMenuDeselected(evt);
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jmReproducirMenuSelected(evt);
            }
        });

        jmCancion1.setBackground(new java.awt.Color(204, 255, 255));
        jmCancion1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jmCancion1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luisf\\OneDrive\\Documentos\\ProyectosJava\\Tarea1HijosDelCodigo\\src iconos\\music_file_icon_238198.png")); // NOI18N
        jmCancion1.setText("Cancion1");
        jmCancion1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jmCancion1.setOpaque(true);
        jmReproducir.add(jmCancion1);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOpaque(true);
        jmReproducir.add(jSeparator1);

        jMenuItem1.setBackground(new java.awt.Color(204, 255, 255));
        jMenuItem1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luisf\\OneDrive\\Documentos\\ProyectosJava\\Tarea1HijosDelCodigo\\src iconos\\music_file_icon_238198.png")); // NOI18N
        jMenuItem1.setText("Cancion2");
        jMenuItem1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jMenuItem1.setOpaque(true);
        jmReproducir.add(jMenuItem1);

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator4.setOpaque(true);
        jmReproducir.add(jSeparator4);

        jMenuItem2.setBackground(new java.awt.Color(204, 255, 255));
        jMenuItem2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luisf\\OneDrive\\Documentos\\ProyectosJava\\Tarea1HijosDelCodigo\\src iconos\\emblemunreadable_93487.png")); // NOI18N
        jMenuItem2.setText("Salir");
        jMenuItem2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jMenuItem2.setOpaque(true);
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jmReproducir.add(jMenuItem2);

        jmbBarraPrincipal.add(jmReproducir);

        jmControles.setBackground(new java.awt.Color(204, 204, 204));
        jmControles.setBorder(null);
        jmControles.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luisf\\OneDrive\\Documentos\\ProyectosJava\\Tarea1HijosDelCodigo\\src iconos\\iconfinder-musicmelodysoundaudio50-4105531_113835.png")); // NOI18N
        jmControles.setMnemonic('C');
        jmControles.setText("Controles");
        jmControles.setOpaque(true);
        jmControles.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
                jmControlesMenuCanceled(evt);
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
                jmControlesMenuDeselected(evt);
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jmControlesMenuSelected(evt);
            }
        });

        jMenu4.setBackground(new java.awt.Color(204, 255, 255));
        jMenu4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jMenu4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luisf\\OneDrive\\Documentos\\ProyectosJava\\Tarea1HijosDelCodigo\\src iconos\\menuoptions_85724.png")); // NOI18N
        jMenu4.setText("Opciones");
        jMenu4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jMenu4.setOpaque(true);

        chkRepetirCancion.setBackground(new java.awt.Color(204, 255, 255));
        chkRepetirCancion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        chkRepetirCancion.setSelected(true);
        chkRepetirCancion.setText("Repetir Canción");
        chkRepetirCancion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        chkRepetirCancion.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luisf\\OneDrive\\Documentos\\ProyectosJava\\Tarea1HijosDelCodigo\\src iconos\\repeatoutline_110883.png")); // NOI18N
        chkRepetirCancion.setOpaque(true);
        chkRepetirCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkRepetirCancionActionPerformed(evt);
            }
        });
        jMenu4.add(chkRepetirCancion);

        jmControles.add(jMenu4);

        jmbBarraPrincipal.add(jmControles);

        modoOscuroItem.setBackground(new java.awt.Color(204, 204, 204));
        modoOscuroItem.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luisf\\OneDrive\\Documentos\\ProyectosJava\\Tarea1HijosDelCodigo\\src iconos\\settings_gear_options_option_icon-icons.com_59985.png")); // NOI18N
        modoOscuroItem.setMnemonic('A');
        modoOscuroItem.setText("Configuración");
        modoOscuroItem.setOpaque(true);
        modoOscuroItem.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
                modoOscuroItemMenuDeselected(evt);
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                modoOscuroItemMenuSelected(evt);
            }
        });

        modoClaroItem.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroup1.add(modoClaroItem);
        modoClaroItem.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        modoClaroItem.setText("Modo Claro");
        modoClaroItem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        modoClaroItem.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luisf\\OneDrive\\Documentos\\ProyectosJava\\Tarea1HijosDelCodigo\\src iconos\\sphere_ball_icon_231267.png")); // NOI18N
        modoClaroItem.setOpaque(true);
        modoClaroItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modoClaroItemActionPerformed(evt);
            }
        });
        modoOscuroItem.add(modoClaroItem);

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator5.setOpaque(true);
        modoOscuroItem.add(jSeparator5);

        jRadioButtonMenuItem1.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroup1.add(jRadioButtonMenuItem1);
        jRadioButtonMenuItem1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Modo Oscuro");
        jRadioButtonMenuItem1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jRadioButtonMenuItem1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luisf\\OneDrive\\Documentos\\ProyectosJava\\Tarea1HijosDelCodigo\\src iconos\\8ballicon_98498.png")); // NOI18N
        jRadioButtonMenuItem1.setOpaque(true);
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        modoOscuroItem.add(jRadioButtonMenuItem1);

        jmbBarraPrincipal.add(modoOscuroItem);

        setJMenuBar(jmbBarraPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmbBarraPrincipalComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jmbBarraPrincipalComponentShown
        System.out.println("La barra principal del menu ahora esta visible");
    }//GEN-LAST:event_jmbBarraPrincipalComponentShown

    private void jmbBarraPrincipalComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jmbBarraPrincipalComponentHidden
        System.out.println("La barra principal del menu ahora esta oculta");
    }//GEN-LAST:event_jmbBarraPrincipalComponentHidden

    private void jmbBarraPrincipalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmbBarraPrincipalMouseEntered
        System.out.println("El mouse entro en la barra principal");
    }//GEN-LAST:event_jmbBarraPrincipalMouseEntered

    private void jmbBarraPrincipalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmbBarraPrincipalMouseExited
        System.out.println("El mouse salio de la barra principal");
    }//GEN-LAST:event_jmbBarraPrincipalMouseExited

    private void jmReproducirMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jmReproducirMenuSelected
       System.out.println("El menu de reproducir esta abierto");
    }//GEN-LAST:event_jmReproducirMenuSelected

    private void jmReproducirMenuDeselected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jmReproducirMenuDeselected
        System.out.println("El menu de reproducir esta cerrado");
    }//GEN-LAST:event_jmReproducirMenuDeselected

    private void jmReproducirMenuCanceled(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jmReproducirMenuCanceled
        System.out.println("El menu de reproducir se cancelo");
    }//GEN-LAST:event_jmReproducirMenuCanceled

    private void jmControlesMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jmControlesMenuSelected
        System.out.println("El menu de controles esta abierto");
    }//GEN-LAST:event_jmControlesMenuSelected

    private void jmControlesMenuDeselected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jmControlesMenuDeselected
        System.out.println("El menu de controles esta cerrado");
    }//GEN-LAST:event_jmControlesMenuDeselected

    private void jmControlesMenuCanceled(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jmControlesMenuCanceled
        System.out.println("El menu de controles se cancelo");
    }//GEN-LAST:event_jmControlesMenuCanceled

    private void modoOscuroItemMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_modoOscuroItemMenuSelected
        System.out.println("El menu de ayuda esta abierto");
    }//GEN-LAST:event_modoOscuroItemMenuSelected

    private void modoOscuroItemMenuDeselected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_modoOscuroItemMenuDeselected
        System.out.println("El menu de ayuda esta cerrado");
    }//GEN-LAST:event_modoOscuroItemMenuDeselected

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed
   // Cambiar el fondo y color del JFrame
   cambiarColores(this.getContentPane(), Color.BLACK, Color.WHITE);

           // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

    private void modoClaroItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modoClaroItemActionPerformed
 cambiarColores(this.getContentPane(), Color.WHITE, Color.BLACK);
       // TODO add your handling code here:
    }//GEN-LAST:event_modoClaroItemActionPerformed
private void cambiarColores(Container contenedor, Color fondo, Color texto) {
    contenedor.setBackground(fondo);

    for (Component c : contenedor.getComponents()) {
        c.setForeground(texto);

        if (c instanceof Container) {
            cambiarColores((Container) c, fondo, texto); // Llama recursivamente a los contenedores internos
        }
    }
}
    private void chkRepetirCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkRepetirCancionActionPerformed
        if (chkRepetirCancion.isSelected()) {
            lblRepetir.setText("Repetir: ON");
        } else {
            lblRepetir.setText("Repetir: OFF");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_chkRepetirCancionActionPerformed

    private void btnAlternarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlternarMenuActionPerformed
        boolean visible = jmbBarraPrincipal.isVisible();
        jmbBarraPrincipal.setVisible(!visible);
    }//GEN-LAST:event_btnAlternarMenuActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Control_JavaSwing_Menus().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Opcion1;
    private javax.swing.JMenuItem Opcion2;
    private javax.swing.JMenuItem SubOpcion;
    private javax.swing.JButton btnAlternarMenu;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBoxMenuItem chkRepetirCancion;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JMenu jmCancion1;
    private javax.swing.JMenu jmControles;
    private javax.swing.JMenu jmReproducir;
    private javax.swing.JMenuBar jmbBarraPrincipal;
    private javax.swing.JLabel lblRepetir;
    private javax.swing.JRadioButtonMenuItem modoClaroItem;
    private javax.swing.JMenu modoOscuroItem;
    // End of variables declaration//GEN-END:variables
}
